services:
  scanner1:
    cap_add:
      - NET_ADMIN
    container_name: scanner1
    build: .
    networks:
      ipvlan-net:
        ipv4_address: 10.0.52.201
    environment:
      - CONT_IP=10.0.52.201
      - DEV_NAME=Custom-Scn1
      - DESTINATION=scan1
    volumes:
      - type: bind
        source: /home/localadmin/scannerApp/scans
        target: /srv/scans


  # scanner2:
  #   container_name: scanner2
  #   build: .
  #   networks:
  #     ipvlan-net:
  #       ipv4_address: 10.0.52.202
  #   environment:
  #     - CONT_IP=10.0.52.202
  #     - DEV_NAME=custom-Scn2
  #     - DESTINATION=scan2
  #   volumes:
  #     - type: bind
  #       source: /home/localadmin/scannerApp/scans
  #       target: /srv/scans

networks:
  ipvlan-net:
    driver: ipvlan
    driver_opts:
      parent: ens19
    ipam:
      config:
        - subnet: 10.0.52.0/24
          gateway: 10.0.52.1

