# Network configuration
network:
  udp_port: 706
  tcp_port: 708
  discovery_timeout: 1.0
  socket_timeout: 1.0
  buffer_size: 1024
  tcp_chunk_size: 1460
  tcp_connection_timeout: 10.0

# Scanner configuration  
scanner:
  default_src_name: "Scanner-Dev"
  max_retry_attempts: 3
  default_file_path: "files/scan.raw"
  files_directory: "files"

# File Transfer Protocol Messages
file_transfer:
  handshake_message: "FILE_TRANSFER_READY"
  size_ok_message: "SIZE_OK"
  complete_message: "FILE_TRANSFER_COMPLETE"
  transfer_ok_message: "TRANSFER_OK"

# Logging configuration
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Agent configuration
agents:
  discovery_interval: 30.0  # seconds
  max_agents: 10
