# Network configuration
network:
  udp_port: 706
  tcp_port: 708
  discovery_timeout: 1.0
  socket_timeout: 1.0
  buffer_size: 1024
  tcp_chunk_size: 1460
  tcp_connection_timeout: 10.0

# Scanner configuration  
scanner:
  default_src_name: "Scanner-Prod"
  max_retry_attempts: 5
  default_file_path: "files/scan.raw"
  files_directory: "files"

# File Transfer Protocol Messages
file_transfer:
  handshake_message: "FILE_TRANSFER_READY"
  size_ok_message: "SIZE_OK"
  complete_message: "FILE_TRANSFER_COMPLETE"
  transfer_ok_message: "TRANSFER_OK"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: true
  file_path: "logs/scanner-prod.log"
  max_file_size: 52428800  # 50MB
  backup_count: 10
  console_enabled: false

# Agent configuration
agents:
  discovery_interval: 60.0  # seconds
  max_agents: 50
